spring:
  application:
    name: appointmentSystem

  datasource:
    url: jdbc:mysql://localhost:3306/officehour_db?allowPublicKeyRetrieval=true&useSSL=false
    username: abdn1
    password: "@Abdn123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.abdofficehour.appointmentsystem.pojo

server:
  port: 8032

custom:
  config:
    main-app-url: http://sso.abdn.kirisame.cc/
    token-url: api/token_verify/

    date-len: 7
    start-hour: 8
    start-miu: 0
    end-hour: 20
    end-miu: 0