spring:
  application:
    name: appointmentSystem

  datasource:
    url: jdbc:mysql://localhost:3306/appointment_system?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.abdofficehour.appointmentsystem.pojo

custom:
  config:
    main-app-url: http://localhost:3000
    token-url: /auth/token